import { Types } from 'mongoose';

const studioNoor = {
  name: 'Studio Noor',
  slug: 'studio-noor',
  tagline: 'Where restraint is the most radical form of luxury.',
  bio: 'Studio Noor is the atelier of Noor Chauhan, one of Delhi\'s most sought-after bridal artists for the discerning minimalist bride. Operating from a private studio in Hauz Khas, Noor has developed a signature method that prioritises skin health over coverage — a multi-session botanical preparation protocol producing a luminous, unretouched finish. Her roster includes brides from the city\'s most established families.',
  profileImageUrl: '/images/studio-noor-profile.png',
  location: {
    microLocation: 'Hauz Khas',
    city: 'New Delhi',
    travelPolicy: 'venue-visits',
    serviceRadius: 20,
  },
  contact: {
    phone: '+91 98101 22334',
    whatsapp: '+91 98101 22334',
    instagram: 'https://instagram.com/studionoor.delhi',
  },
  businessMeta: {
    yearsOfExperience: 14,
    teamSize: 3,
    languagesSpoken: ['Hindi', 'English'],
    bookingLeadTimeDays: 45,
    trialsOffered: true,
    trialDurationMinutes: 180,
  },
  pricing: {
    tier: 'ultra-luxury',
    startingFromINR: 95000,
    currency: 'INR',
    travelSurchargePerKm: 400,
  },
  aestheticProfile: {
    styleArchetypes: ['sabyasachi-minimalist', 'raw-mango-organic'],
    makeupFinishTags: ['no-makeup-makeup', 'satin-glow'],
    hairStyleTags: ['gajra-forward-traditional', 'sleek-low-bun-couture'],
    occasionSpecializations: ['wedding-day-bridal', 'pre-wedding-shoot', 'cocktail-pre-wedding'],
    colorPaletteAffinity: ['ivory-and-gold-neutral', 'earth-and-terracotta-organic'],
    skinToneExpertise: ['pan-spectrum-expert', 'wheatish-warm-undertone'],
    inspirationReferences: ['Sabyasachi Mukherjee', 'Raw Mango', 'Anju Modi'],
    signatureElements: 'Single mogra strand placed at the hairline rather than a crown, combined with a bare satin-finish base achieved through a three-session botanical prep protocol preceding the event day.',
    aestheticBio: 'Noor Chauhan works in the register of quiet authority. Her brides are edited, not decorated — skin prepped over multiple sessions with botanical protocols, lips left near-bare, eyes traced with a single deliberate line. She counts among her signatures a mogra placement so specific it has appeared in three bridal editorials. Her ideal client already knows what she wants to remove.',
    moodKeywords: ['restrained', 'luminous', 'botanical', 'heritage', 'quiet'],
    contraIndicators: ['no-heavy-contouring', 'no-airbrush'],
    contraIndicatorsNotes: 'Noor works exclusively with skin-forward techniques. Heavy contouring distorts the skin quality she spends multiple sessions building. Airbrush compromises the tactile finish she is known for.',
  },
  portfolio: [
    {
      imageUrl: '/images/studio-noor-portfolio-01.png',
      altText: 'Studio Noor bridal look — ivory Raw Mango handloom with mogra hairline placement',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['sabyasachi-minimalist'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'earth-and-terracotta-organic'],
      captionForAI: 'Bride in ivory Raw Mango handloom, terracotta border. Bare satin skin, kohl waterline only. Single mogra strand at hairline. Loose braid. Antique gold jhumka. Morning diffused light.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/studio-noor-portfolio-02.png',
      altText: 'Studio Noor bridal look — unbleached Chanderi silk with low chignon',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['sabyasachi-minimalist', 'raw-mango-organic'],
      colorPaletteShown: ['ivory-and-gold-neutral'],
      captionForAI: 'Bride in unbleached Chanderi silk. No-makeup skin, defined brow. Low chignon, single jasmine sprig. Pearl strand earring. Ivory and dusty rose. Overcast natural light.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/studio-noor-portfolio-03.png',
      altText: 'Studio Noor pre-wedding shoot — sage handloom cotton saree',
      primaryOccasion: 'pre-wedding-shoot',
      styleArchetypesShown: ['raw-mango-organic'],
      colorPaletteShown: ['earth-and-terracotta-organic', 'ivory-and-gold-neutral'],
      captionForAI: 'Pre-wedding shoot. Bride in sage handloom cotton. Glass-skin finish, no colour. Hair down, natural wave. Sage, ivory, terracotta. Golden hour backlight.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/studio-noor-portfolio-03.png',
      altText: 'Studio Noor cocktail look — ivory brocade lehenga',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['sabyasachi-minimalist'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'champagne-and-blush-soft'],
      captionForAI: 'Cocktail evening. Ivory brocade lehenga, antique gold thread. Satin skin, single liner stroke, nude lip. Sleek low bun, one mogra sprig. Ivory, champagne. Studio soft box.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.9,
    totalReviews: 47,
    skillScore: 5.0,
    punctualityScore: 4.8,
    communicationScore: 4.9,
    valueScore: 4.7,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: true,
    badgeType: 'The Cartel Core',
  },
};

const meherAtelier = {
  name: 'Meher Atelier',
  slug: 'meher-atelier',
  tagline: 'A lineage of Mughlai beauty, preserved for the modern bride.',
  bio: 'Meher Reza has built her reputation over sixteen years as the foremost custodian of Delhi\'s Mughlai bridal tradition. Her Defence Colony atelier is appointment-only, accommodating only two bridal clients per month to ensure the depth of preparation each look demands. She is the only makeup artist in Delhi who still sources and prepares her own kohl compound using a traditional Lucknowi recipe.',
  profileImageUrl: '/images/meher-atelier-profile.png',
  location: {
    microLocation: 'Defence Colony',
    city: 'New Delhi',
    travelPolicy: 'venue-visits',
    serviceRadius: 18,
  },
  contact: {
    phone: '+91 99100 33445',
    whatsapp: '+91 99100 33445',
    instagram: 'https://instagram.com/meheratelier',
  },
  businessMeta: {
    yearsOfExperience: 16,
    teamSize: 4,
    languagesSpoken: ['Hindi', 'English', 'Urdu'],
    bookingLeadTimeDays: 60,
    trialsOffered: true,
    trialDurationMinutes: 210,
  },
  pricing: {
    tier: 'ultra-luxury',
    startingFromINR: 115000,
    currency: 'INR',
    travelSurchargePerKm: 500,
  },
  aestheticProfile: {
    styleArchetypes: ['heavy-royal-mughlai', 'old-delhi-heritage'],
    makeupFinishTags: ['smoky-kohl-eye', 'airbrush-finish', 'satin-glow'],
    hairStyleTags: ['gajra-forward-traditional', 'structured-updo'],
    occasionSpecializations: ['wedding-day-bridal', 'sangeet-night-glam', 'baraat-reception'],
    colorPaletteAffinity: ['jewel-tone-maximalist', 'saffron-and-vermillion-traditional', 'ivory-and-gold-neutral'],
    skinToneExpertise: ['pan-spectrum-expert', 'deep-and-rich', 'wheatish-warm-undertone'],
    inspirationReferences: ['Abu Jani Sandeep Khosla', 'Sabyasachi Mukherjee', 'Old Bollywood — Meena Kumari'],
    signatureElements: 'A custom kohl compound applied in extended Mughlai style — three progressive coats blended to the orbital bone — paired with a gold passa structure rising four centimetres above the parting.',
    aestheticBio: 'Meher Reza is the inheritor of a Mughlai bridal vocabulary that belongs to Old Delhi\'s walled city. Her brides are sovereign: kohl applied in unhurried extended strokes, gold passa structures rising from mogra-woven braids, skin at a luminous finish that recalls old miniature portraiture. She does not offer a look. She is offering entry into a four-hundred-year lineage.',
    moodKeywords: ['sovereign', 'regal', 'ancestral', 'opulent', 'ceremonial'],
    contraIndicators: ['no-heavy-contouring'],
    contraIndicatorsNotes: 'Meher\'s Mughlai technique relies on skin that reads as naturally luminous. Heavy contouring introduces a modernity that disrupts the visual grammar of the traditional look she constructs.',
  },
  portfolio: [
    {
      imageUrl: '/images/meher-atelier-portfolio-01.png',
      altText: 'Meher Atelier bridal look — deep crimson Banarasi with Mughlai kohl',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['heavy-royal-mughlai', 'old-delhi-heritage'],
      colorPaletteShown: ['saffron-and-vermillion-traditional', 'ivory-and-gold-neutral'],
      captionForAI: 'Bride in deep crimson Banarasi, heavy gold zari. Extended kohl-smudged eye to orbital bone. Luminous matte airbrush skin. Gold passa structure, mogra braid. Vermillion sindoor. Candlelit mandap.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/meher-atelier-portfolio-02.png',
      altText: 'Meher Atelier sangeet look — royal blue lehenga with heavy cut crease',
      primaryOccasion: 'sangeet-night-glam',
      styleArchetypesShown: ['heavy-royal-mughlai'],
      colorPaletteShown: ['jewel-tone-maximalist', 'ivory-and-gold-neutral'],
      captionForAI: 'Sangeet night. Bride in royal blue sequin lehenga, gold embroidery. Heavy kohl cut crease, champagne shadow. Luminous skin. Chandelier earrings. Gold passa. Cobalt, gold. Stage lighting.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/meher-atelier-portfolio-03.png',
      altText: 'Meher Atelier baraat look — deep teal silk with Mughlai updo',
      primaryOccasion: 'baraat-reception',
      styleArchetypesShown: ['heavy-royal-mughlai'],
      colorPaletteShown: ['jewel-tone-maximalist', 'deep-burgundy-and-plum-moody'],
      captionForAI: 'Baraat reception. Deep teal silk saree. Kohl-heavy extended eye, plum lip. Structured Mughlai updo with gold passa. Warm bronze skin. Teal, gold, plum. Evening warm interior.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/meher-atelier-portfolio-03.png',
      altText: 'Meher Atelier mehendi look — mustard tissue silk',
      primaryOccasion: 'mehendi-ceremony',
      styleArchetypesShown: ['old-delhi-heritage'],
      colorPaletteShown: ['saffron-and-vermillion-traditional', 'earth-and-terracotta-organic'],
      captionForAI: 'Mehendi ceremony. Mustard tissue silk saree. Bare luminous skin, terracotta lip stain. Loose mogra braid, fresh marigolds. Kohl waterline only. Saffron, mustard, ivory. Outdoor morning light.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 5.0,
    totalReviews: 31,
    skillScore: 5.0,
    punctualityScore: 5.0,
    communicationScore: 5.0,
    valueScore: 4.5,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: true,
    badgeType: 'Heritage Master',
  },
};

const studioAara = {
  name: 'Studio Aara',
  slug: 'studio-aara',
  tagline: 'Your skin, but sharper. No filter required.',
  bio: 'Studio Aara, led by Aara Singh, is the destination for brides who plan their wedding looks around photography. Operating from a full-service studio in South Extension, Aara\'s approach is grounded in a Korean skin preparation philosophy combined with the technical demands of professional digital photography. Her clients frequently report zero retouching required across their entire wedding album.',
  profileImageUrl: '/images/studio-aara-profile.png',
  location: {
    microLocation: 'South Extension',
    city: 'New Delhi',
    travelPolicy: 'all',
    serviceRadius: 25,
  },
  contact: {
    phone: '+91 98115 44556',
    whatsapp: '+91 98115 44556',
    instagram: 'https://instagram.com/studioaara',
    website: 'https://studioaara.in',
  },
  businessMeta: {
    yearsOfExperience: 10,
    teamSize: 3,
    languagesSpoken: ['Hindi', 'English'],
    bookingLeadTimeDays: 30,
    trialsOffered: true,
    trialDurationMinutes: 150,
  },
  pricing: {
    tier: 'luxury',
    startingFromINR: 75000,
    currency: 'INR',
    travelSurchargePerKm: 300,
  },
  aestheticProfile: {
    styleArchetypes: ['glass-skin-glam', 'contemporary-editorial'],
    makeupFinishTags: ['dewy-glass-skin', 'airbrush-finish', 'no-makeup-makeup'],
    hairStyleTags: ['sleek-low-bun-couture', 'loose-boho-waves'],
    occasionSpecializations: ['wedding-day-bridal', 'pre-wedding-shoot', 'cocktail-pre-wedding'],
    colorPaletteAffinity: ['champagne-and-blush-soft', 'ivory-and-gold-neutral'],
    skinToneExpertise: ['fair-and-porcelain', 'wheatish-warm-undertone', 'pan-spectrum-expert'],
    inspirationReferences: ['Tarun Tahiliani', 'Contemporary Bollywood — Deepika Padukone', 'Western Vogue Bridal'],
    signatureElements: 'A twelve-step Korean skin preparation beginning forty-eight hours before event day, producing a dewy base requiring zero powder and photographing without correction.',
    aestheticBio: 'Aara Singh trained under a Seoul-based skin specialist and spent four years as a set artist on premium streaming productions. She builds skin — never covers it. Her preparation yields a dewy, camera-optimised base photographing identically under natural light and professional flash. The result is a bride who needs no editing, no filter, no apology.',
    moodKeywords: ['glass-skin', 'cinematic', 'editorial', 'precise', 'luminous'],
    contraIndicators: [],
  },
  portfolio: [
    {
      imageUrl: '/images/studio-aara-portfolio-01.png',
      altText: 'Studio Aara bridal look — champagne chiffon with glass-skin base',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['glass-skin-glam'],
      colorPaletteShown: ['champagne-and-blush-soft', 'ivory-and-gold-neutral'],
      captionForAI: 'Bride in champagne chiffon, gold threadwork. Dewy glass-skin, zero powder. Inner corner highlight only. Sleek low bun, single gold chain. Champagne, ivory. Natural window light.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/studio-aara-portfolio-02.png',
      altText: 'Studio Aara pre-wedding shoot — ivory structured gown',
      primaryOccasion: 'pre-wedding-shoot',
      styleArchetypesShown: ['contemporary-editorial', 'glass-skin-glam'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'champagne-and-blush-soft'],
      captionForAI: 'Pre-wedding shoot. Ivory structured gown, pearl embellishment. Luminous skin, defined brow, clear gloss. Hair loose, silk-press finish. Ivory, pearl, gold. Sunrise natural light.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/studio-aara-portfolio-03.png',
      altText: 'Studio Aara cocktail look — emerald velvet lehenga',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['glass-skin-glam', 'contemporary-editorial'],
      colorPaletteShown: ['jewel-tone-maximalist'],
      captionForAI: 'Cocktail function. Emerald velvet lehenga. Glass-skin base, smoked lower lash only, berry lip. Structured half-updo, emerald drop earring. Emerald, gold. Evening warm light.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/studio-aara-portfolio-03.png',
      altText: 'Studio Aara engagement look — blush pink organza',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['glass-skin-glam'],
      colorPaletteShown: ['champagne-and-blush-soft'],
      captionForAI: 'Engagement ceremony. Blush organza lehenga. Dewy skin-first base, peach blush, defined mascara. Hair in loose waves, blush florals. Blush, champagne, rose gold. Diffused studio light.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.8,
    totalReviews: 62,
    skillScore: 4.9,
    punctualityScore: 4.8,
    communicationScore: 4.9,
    valueScore: 4.6,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: true,
    badgeType: 'Vanguard Stylist',
  },
};

const priyaBhandariArtistry = {
  name: 'Priya Bhandari Artistry',
  slug: 'priya-bhandari-artistry',
  tagline: 'For the bride who enters her wedding like a film scene.',
  bio: 'Priya Bhandari spent eight years on Bollywood production sets before opening her private studio in Greater Kailash, and the cinematic sensibility of that training is immediately legible in her work. She is the go-to artist for the bride who wants her wedding to feel like a film — controlled, crafted, visually arresting. Her studio books a minimum of six months in advance during the Delhi wedding season.',
  profileImageUrl: '/images/priya-bhandari-artistry-profile.png',
  location: {
    microLocation: 'Greater Kailash I',
    city: 'New Delhi',
    travelPolicy: 'all',
    serviceRadius: 22,
  },
  contact: {
    phone: '+91 99909 55667',
    whatsapp: '+91 99909 55667',
    instagram: 'https://instagram.com/priyabhandari.artistry',
  },
  businessMeta: {
    yearsOfExperience: 12,
    teamSize: 3,
    languagesSpoken: ['Hindi', 'English'],
    bookingLeadTimeDays: 30,
    trialsOffered: false,
  },
  pricing: {
    tier: 'luxury',
    startingFromINR: 72000,
    currency: 'INR',
    travelSurchargePerKm: 300,
  },
  aestheticProfile: {
    styleArchetypes: ['manish-malhotra-shimmer', 'dark-romanticism'],
    makeupFinishTags: ['dramatic-cut-crease', 'glitter-foil-statement', 'hd-matte-flash'],
    hairStyleTags: ['sleek-low-bun-couture', 'structured-updo', 'extension-and-volume'],
    occasionSpecializations: ['sangeet-night-glam', 'wedding-day-bridal', 'cocktail-pre-wedding', 'baraat-reception'],
    colorPaletteAffinity: ['deep-burgundy-and-plum-moody', 'jewel-tone-maximalist', 'champagne-and-blush-soft'],
    skinToneExpertise: ['pan-spectrum-expert', 'wheatish-warm-undertone', 'fair-and-porcelain'],
    inspirationReferences: ['Manish Malhotra', 'Contemporary Bollywood — Kareena Kapoor', 'Architectural — Valentino Couture'],
    signatureElements: 'A dual-tone cut crease in champagne and graphite executed with a hand-cut flat shader, combined with a plum-to-nude lip gradient blended on the lip line itself rather than over it.',
    aestheticBio: 'Priya Bhandari trained on Bollywood sets, constructing looks that hold conviction at forty feet. Her bridal vocabulary is cinematic: deep plum gradient lips, smoked cut crease in champagne and graphite, a champagne highlight sitting precisely on the brow bone. A Priya bride does not walk into her wedding. She enters it.',
    moodKeywords: ['cinematic', 'dramatic', 'moody', 'champagne', 'smouldering'],
    contraIndicators: ['no-at-home-service'],
    contraIndicatorsNotes: 'Priya\'s technique requires her full studio lighting rig and camera monitoring setup. All clients attend the Greater Kailash studio exclusively.',
  },
  portfolio: [
    {
      imageUrl: '/images/priya-bhandari-artistry-portfolio-01.png',
      altText: 'Priya Bhandari bridal look — deep burgundy sequin lehenga with cut crease',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['manish-malhotra-shimmer', 'dark-romanticism'],
      colorPaletteShown: ['deep-burgundy-and-plum-moody', 'champagne-and-blush-soft'],
      captionForAI: 'Bride in deep burgundy sequin lehenga. Smoked cut crease, champagne and graphite. Plum-to-nude gradient lip. HD skin, champagne brow bone highlight. Low chignon. Burgundy, champagne, graphite.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/priya-bhandari-artistry-portfolio-02.png',
      altText: 'Priya Bhandari sangeet look — gold and black sequin saree',
      primaryOccasion: 'sangeet-night-glam',
      styleArchetypesShown: ['manish-malhotra-shimmer'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'jewel-tone-maximalist'],
      captionForAI: 'Sangeet night. Gold and black sequin saree. Dramatic liner, deep kohl waterline. Bronze skin, champagne highlight on brow bone. Hair in high-volume loose curls. Gold, black. Stage backlighting.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/priya-bhandari-artistry-portfolio-03.png',
      altText: 'Priya Bhandari cocktail look — sapphire blue velvet gown',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['dark-romanticism', 'contemporary-editorial'],
      colorPaletteShown: ['jewel-tone-maximalist', 'monochrome-editorial'],
      captionForAI: 'Cocktail evening. Sapphire velvet gown. Navy and silver cut crease, foil inner corner. Satin skin. Statement updo, sapphire drop earring. Sapphire, silver. Evening directional spotlight.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/priya-bhandari-artistry-portfolio-03.png',
      altText: 'Priya Bhandari pre-wedding shoot — champagne sequin lehenga',
      primaryOccasion: 'pre-wedding-shoot',
      styleArchetypesShown: ['manish-malhotra-shimmer'],
      colorPaletteShown: ['champagne-and-blush-soft', 'ivory-and-gold-neutral'],
      captionForAI: 'Pre-wedding shoot. Champagne sequin lehenga. Glitter eye, sharp wing liner, nude lip. Dewy skin, gold highlight. Half-down hair, beachy wave texture. Champagne, gold, ivory.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.8,
    totalReviews: 89,
    skillScore: 4.9,
    punctualityScore: 4.7,
    communicationScore: 4.8,
    valueScore: 4.7,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: true,
    badgeType: 'The Cartel Core',
  },
};

const theRiyaEdit = {
  name: 'The Riya Edit',
  slug: 'the-riya-edit',
  tagline: 'South Delhi restraint. Paris precision. One bride at a time.',
  bio: 'Riya Khanna returned to Delhi from Paris with a disciplined restraint rarely found in the bridal market. Her Vasant Vihar studio serves a tight clientele of brides who understand that luxury is expressed through precision, not excess. Her aesthetic vocabulary is that of a couture atelier — measured, considered, unerringly composed. She accepts no more than twenty bridal clients per year.',
  profileImageUrl: '/images/the-riya-edit-profile.png',
  location: {
    microLocation: 'Vasant Vihar',
    city: 'New Delhi',
    travelPolicy: 'all',
    serviceRadius: 25,
  },
  contact: {
    phone: '+91 98105 66778',
    whatsapp: '+91 98105 66778',
    instagram: 'https://instagram.com/theriyaedit',
    website: 'https://theriyaedit.com',
  },
  businessMeta: {
    yearsOfExperience: 9,
    teamSize: 2,
    languagesSpoken: ['Hindi', 'English', 'French'],
    bookingLeadTimeDays: 30,
    trialsOffered: true,
    trialDurationMinutes: 120,
  },
  pricing: {
    tier: 'luxury',
    startingFromINR: 65000,
    currency: 'INR',
    travelSurchargePerKm: 250,
  },
  aestheticProfile: {
    styleArchetypes: ['south-delhi-chic', 'indo-western-fusion'],
    makeupFinishTags: ['satin-glow', 'no-makeup-makeup', 'dramatic-cut-crease'],
    hairStyleTags: ['sleek-low-bun-couture', 'structured-updo', 'loose-boho-waves'],
    occasionSpecializations: ['wedding-day-bridal', 'pre-wedding-shoot', 'cocktail-pre-wedding'],
    colorPaletteAffinity: ['champagne-and-blush-soft', 'monochrome-editorial', 'ivory-and-gold-neutral'],
    skinToneExpertise: ['fair-and-porcelain', 'wheatish-warm-undertone'],
    inspirationReferences: ['Anju Modi', 'Western Vogue Bridal', 'Sabyasachi Mukherjee'],
    signatureElements: 'A structured silk-press blowout creating the appearance of effortless texture — volume at the root, weight at the ends — styled to frame the jawline and expose the neckline architecture.',
    aestheticBio: 'Riya Khanna spent seven years in a Parisian couture atelier before returning to South Delhi, and the discipline is visible in every finish. She works in old-money restraint — clean skin, one precise liner stroke, hair structured but never architectural. Her brides look as though they have never tried too hard, which is, of course, the most demanding thing to achieve.',
    moodKeywords: ['restrained', 'old-money', 'couture', 'composed', 'refined'],
    contraIndicators: ['no-airbrush', 'no-heavy-contouring'],
    contraIndicatorsNotes: 'Riya\'s approach requires direct hand application to achieve the precise tonal gradients and skin texture her look demands. Airbrush and heavy contouring both undermine the couture finish she delivers.',
  },
  portfolio: [
    {
      imageUrl: '/images/the-riya-edit-portfolio-01.png',
      altText: 'The Riya Edit bridal look — ivory silk organza with pearl border',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['south-delhi-chic'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'champagne-and-blush-soft'],
      captionForAI: 'Bride in ivory silk organza, pearl border. One precise liner stroke, blush cheek. Structured silk-press blowout framing jaw. Single pearl strand earring. Ivory, champagne. Overcast morning light.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/the-riya-edit-portfolio-02.png',
      altText: 'The Riya Edit engagement look — champagne linen coord',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['south-delhi-chic', 'indo-western-fusion'],
      colorPaletteShown: ['champagne-and-blush-soft', 'monochrome-editorial'],
      captionForAI: 'Engagement ceremony. Champagne linen coord. Skin-first base, defined brow, nude gloss. Hair in a clean knot, single geometric hairpin. Champagne, ivory. Natural afternoon indoor light.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/the-riya-edit-portfolio-03.png',
      altText: 'The Riya Edit cocktail look — midnight blue column saree',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['indo-western-fusion', 'south-delhi-chic'],
      colorPaletteShown: ['monochrome-editorial', 'jewel-tone-maximalist'],
      captionForAI: 'Cocktail evening. Midnight blue column drape saree. Precise liner, deep rose lip, clean skin. Low tight chignon, geometric gold clip. Navy, gold. Architectural interior ambient light.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/the-riya-edit-portfolio-03.png',
      altText: 'The Riya Edit pre-wedding shoot — raw silk off-shoulder',
      primaryOccasion: 'pre-wedding-shoot',
      styleArchetypesShown: ['south-delhi-chic'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'earth-and-terracotta-organic'],
      captionForAI: 'Pre-wedding shoot. Raw silk off-shoulder top with draped skirt. No-makeup skin, clear brow, single coat mascara. Hair loose, air-dried texture. Ivory, terracotta. Golden hour.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.9,
    totalReviews: 24,
    skillScore: 5.0,
    punctualityScore: 4.9,
    communicationScore: 4.8,
    valueScore: 4.8,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: false,
    badgeType: null,
  },
};

const kamakshiAndCo = {
  name: 'Kamakshi & Co.',
  slug: 'kamakshi-and-co',
  tagline: 'Full coverage. Full colour. Full confidence.',
  bio: 'Kamakshi Iyer is Karol Bagh\'s most beloved bridal makeup studio, operating for eleven years and serving over four hundred brides. Her studio is built for Punjabi grandeur — maximum coverage, maximum colour saturation, maximum durability. She employs a team of four trained artists and is the only studio in North Delhi to offer an on-site airbrush barrier service specifically engineered for outdoor summer weddings.',
  profileImageUrl: '/images/kamakshi-and-co-profile.png',
  location: {
    microLocation: 'Karol Bagh',
    city: 'New Delhi',
    travelPolicy: 'all',
    serviceRadius: 30,
  },
  contact: {
    phone: '+91 99100 77889',
    whatsapp: '+91 99100 77889',
    instagram: 'https://instagram.com/kamakshiandco',
  },
  businessMeta: {
    yearsOfExperience: 11,
    teamSize: 4,
    languagesSpoken: ['Hindi', 'English', 'Punjabi'],
    bookingLeadTimeDays: 14,
    trialsOffered: false,
  },
  pricing: {
    tier: 'premium',
    startingFromINR: 35000,
    currency: 'INR',
    travelSurchargePerKm: 150,
  },
  aestheticProfile: {
    styleArchetypes: ['punjabi-grandeur', 'pastel-dreamscape'],
    makeupFinishTags: ['airbrush-finish', 'glitter-foil-statement', 'dramatic-cut-crease'],
    hairStyleTags: ['gajra-forward-traditional', 'heavy-floral-crown', 'extension-and-volume'],
    occasionSpecializations: ['wedding-day-bridal', 'sangeet-night-glam', 'mehendi-ceremony', 'baraat-reception'],
    colorPaletteAffinity: ['pastel-multicolor', 'jewel-tone-maximalist', 'saffron-and-vermillion-traditional'],
    skinToneExpertise: ['pan-spectrum-expert', 'wheatish-warm-undertone', 'fair-and-porcelain'],
    inspirationReferences: ['Manish Malhotra', 'Tarun Tahiliani'],
    signatureElements: 'A double-layer airbrush application for heat durability: HD base applied in two passes with a twenty-minute dry interval, sealed with a theatrical-grade barrier spray engineered for outdoor summer conditions.',
    aestheticBio: 'Kamakshi Iyer built her studio for the bride who refuses to disappear into her own wedding. Maximum coverage, maximum colour, airbrush base rated for twelve-hour outdoor durability. Her bridal configurations are engineered for baraat heat and direct afternoon light — vivid, unapologetic, designed to look flawless in the tenth hour of dancing.',
    moodKeywords: ['vivid', 'celebratory', 'unapologetic', 'durable', 'maximalist'],
    contraIndicators: ['no-synthetic-extensions'],
    contraIndicatorsNotes: 'Kamakshi works exclusively with natural and ethically sourced hair extensions to maintain the integrity and health of the client\'s natural hair during extended wear.',
  },
  portfolio: [
    {
      imageUrl: '/images/kamakshi-and-co-portfolio-01.png',
      altText: 'Kamakshi & Co bridal look — fuchsia Punjabi lehenga with gajra crown',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['punjabi-grandeur'],
      colorPaletteShown: ['pastel-multicolor', 'jewel-tone-maximalist'],
      captionForAI: 'Bride in fuchsia Punjabi lehenga, heavy gold embroidery. Airbrush full-coverage base, deep pink cut crease, glitter inner corner. Full gajra crown. Fuchsia, gold. Outdoor midday sun.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/kamakshi-and-co-portfolio-02.png',
      altText: 'Kamakshi & Co sangeet look — orange and gold lehenga choli',
      primaryOccasion: 'sangeet-night-glam',
      styleArchetypesShown: ['punjabi-grandeur'],
      colorPaletteShown: ['saffron-and-vermillion-traditional', 'jewel-tone-maximalist'],
      captionForAI: 'Sangeet night. Orange and gold lehenga choli. Sequin eye shadow, kohl waterline, coral lip. Full airbrush base. Volume curls with orange flower cluster. Orange, gold, coral. Event stage lighting.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/kamakshi-and-co-portfolio-03.png',
      altText: 'Kamakshi & Co mehendi look — yellow and green dupatta with marigolds',
      primaryOccasion: 'mehendi-ceremony',
      styleArchetypesShown: ['pastel-dreamscape'],
      colorPaletteShown: ['pastel-multicolor', 'saffron-and-vermillion-traditional'],
      captionForAI: 'Mehendi ceremony. Yellow silk kurta, green dupatta. Green glitter eye, saffron lip stain. Loose braid with marigolds and mogra. Saffron, yellow, green. Garden outdoor setting.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/kamakshi-and-co-portfolio-03.png',
      altText: 'Kamakshi & Co baraat look — hot pink and gold Anarkali',
      primaryOccasion: 'baraat-reception',
      styleArchetypesShown: ['punjabi-grandeur'],
      colorPaletteShown: ['jewel-tone-maximalist', 'deep-burgundy-and-plum-moody'],
      captionForAI: 'Baraat reception. Hot pink Anarkali, gold border. Full coverage airbrush, purple smoky eye, berry lip. High volume bun, gold maang tikka, layered necklace. Fuchsia, purple, gold. Venue evening.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.7,
    totalReviews: 156,
    skillScore: 4.8,
    punctualityScore: 4.8,
    communicationScore: 4.6,
    valueScore: 4.9,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: false,
    badgeType: 'Vanguard Stylist',
  },
};

const safiyaStudio = {
  name: 'Safiya Studio',
  slug: 'safiya-studio',
  tagline: 'Not pretty. Precise. The bridal edit for the fashion-conscious bride.',
  bio: 'Safiya Khan is the bridal artist for the fashion-forward Delhi bride. Based in Greater Kailash II, her editorial approach has earned her features in Vogue India, Harper\'s Bazaar Bride, and Brides Today. She has collaborated with five leading fashion photographers and her portfolio has become a reference point for contemporary bridal aesthetics in the capital. Her studio operates by consultation-first appointment only.',
  profileImageUrl: '/images/safiya-studio-profile.png',
  location: {
    microLocation: 'Greater Kailash II',
    city: 'New Delhi',
    travelPolicy: 'all',
    serviceRadius: 22,
  },
  contact: {
    phone: '+91 98107 88990',
    whatsapp: '+91 98107 88990',
    instagram: 'https://instagram.com/safiyastudio',
    website: 'https://safiyastudio.in',
  },
  businessMeta: {
    yearsOfExperience: 11,
    teamSize: 2,
    languagesSpoken: ['Hindi', 'English'],
    bookingLeadTimeDays: 30,
    trialsOffered: true,
    trialDurationMinutes: 150,
  },
  pricing: {
    tier: 'luxury',
    startingFromINR: 70000,
    currency: 'INR',
    travelSurchargePerKm: 280,
  },
  aestheticProfile: {
    styleArchetypes: ['contemporary-editorial', 'glass-skin-glam'],
    makeupFinishTags: ['dewy-glass-skin', 'dramatic-cut-crease', 'no-makeup-makeup'],
    hairStyleTags: ['sleek-low-bun-couture', 'structured-updo'],
    occasionSpecializations: ['pre-wedding-shoot', 'cocktail-pre-wedding', 'wedding-day-bridal', 'sangeet-night-glam'],
    colorPaletteAffinity: ['monochrome-editorial', 'champagne-and-blush-soft', 'ivory-and-gold-neutral'],
    skinToneExpertise: ['pan-spectrum-expert', 'fair-and-porcelain', 'olive-mediterranean'],
    inspirationReferences: ['Contemporary Bollywood — Alia Bhatt', 'Western Vogue Bridal', 'Architectural — Valentino Couture'],
    signatureElements: 'A graphic liner executed with a single-stroke technique — no blending — producing an angular edge that photographs as editorial under both natural and artificial light.',
    aestheticBio: 'Safiya Khan approaches every brief as a fashion editor approaches a cover — with one singular, uncompromising concept. Her portfolio is a decade of glass-skin experiments and architectural liner angles that have appeared in three national bridal publications. She is not interested in pretty. She is interested in precise.',
    moodKeywords: ['editorial', 'architectural', 'precise', 'minimal', 'striking'],
    contraIndicators: ['no-heavy-contouring'],
  },
  portfolio: [
    {
      imageUrl: '/images/safiya-studio-portfolio-01.png',
      altText: 'Safiya Studio bridal look — ivory asymmetric drape with angular liner',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['contemporary-editorial'],
      colorPaletteShown: ['ivory-and-gold-neutral', 'monochrome-editorial'],
      captionForAI: 'Bride in ivory asymmetric drape, structural pleating. Glass-skin base, single-stroke angular graphic liner, bare lip. Sleek side-parted low bun. Ivory, white, gold. Studio directional light.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/safiya-studio-portfolio-02.png',
      altText: 'Safiya Studio pre-wedding shoot — monochrome white coord',
      primaryOccasion: 'pre-wedding-shoot',
      styleArchetypesShown: ['contemporary-editorial', 'glass-skin-glam'],
      colorPaletteShown: ['monochrome-editorial', 'ivory-and-gold-neutral'],
      captionForAI: 'Pre-wedding shoot. Monochrome white coord, architectural pleating. Skin-first base, graphic angular liner, no colour. Hair slicked back. White, ivory. High-contrast editorial light.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/safiya-studio-portfolio-03.png',
      altText: 'Safiya Studio cocktail look — champagne structured gown',
      primaryOccasion: 'cocktail-pre-wedding',
      styleArchetypesShown: ['contemporary-editorial', 'glass-skin-glam'],
      colorPaletteShown: ['champagne-and-blush-soft', 'ivory-and-gold-neutral'],
      captionForAI: 'Cocktail evening. Champagne structured gown, sharp shoulders. Foil eye liner, satin skin, champagne gloss. Architectural updo, single diamond drop. Champagne, gold, ivory. Spotlight.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/safiya-studio-portfolio-03.png',
      altText: 'Safiya Studio sangeet look — deep green draped saree',
      primaryOccasion: 'sangeet-night-glam',
      styleArchetypesShown: ['contemporary-editorial'],
      colorPaletteShown: ['jewel-tone-maximalist', 'ivory-and-gold-neutral'],
      captionForAI: 'Sangeet night. Deep green draped saree, unfinished hem. Smoked kohl liner, glossy nude lip. Loose textured hair, single gold chain. Deep green, ivory, gold. Candlelight interior.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.9,
    totalReviews: 41,
    skillScore: 5.0,
    punctualityScore: 4.8,
    communicationScore: 4.9,
    valueScore: 4.7,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: false,
    badgeType: null,
  },
};

const theMalviyaBride = {
  name: 'The Malviya Bride',
  slug: 'the-malviya-bride',
  tagline: 'Three generations of the only way a Delhi bride is supposed to look.',
  bio: 'Savitri Kapoor is a third-generation makeup artist operating from her grandmother\'s original studio space in Malviya Nagar. She has served over six hundred brides across three decades and has developed a following among families who reject the trend-driven aesthetic of contemporary bridal beauty in favour of a look that is architecturally and ceremonially correct. Her work has been described as documentary-quality traditional bridal artistry.',
  profileImageUrl: '/images/the-malviya-bride-profile.png',
  location: {
    microLocation: 'Malviya Nagar',
    city: 'New Delhi',
    travelPolicy: 'studio-only',
    serviceRadius: 0,
  },
  contact: {
    phone: '+91 98108 99001',
    whatsapp: '+91 98108 99001',
    instagram: 'https://instagram.com/themalviyabride',
  },
  businessMeta: {
    yearsOfExperience: 28,
    teamSize: 2,
    languagesSpoken: ['Hindi', 'English'],
    bookingLeadTimeDays: 21,
    trialsOffered: false,
  },
  pricing: {
    tier: 'premium',
    startingFromINR: 28000,
    currency: 'INR',
    travelSurchargePerKm: 0,
  },
  aestheticProfile: {
    styleArchetypes: ['old-delhi-heritage', 'heavy-royal-mughlai'],
    makeupFinishTags: ['smoky-kohl-eye', 'matte-velvet', 'satin-glow'],
    hairStyleTags: ['gajra-forward-traditional', 'structured-updo'],
    occasionSpecializations: ['wedding-day-bridal', 'mehendi-ceremony', 'baraat-reception', 'haldi-ceremony'],
    colorPaletteAffinity: ['saffron-and-vermillion-traditional', 'ivory-and-gold-neutral', 'jewel-tone-maximalist'],
    skinToneExpertise: ['pan-spectrum-expert', 'wheatish-warm-undertone', 'deep-and-rich'],
    inspirationReferences: ['Old Bollywood — Waheeda Rehman', 'Sabyasachi Mukherjee', 'Anju Modi'],
    signatureElements: 'The traditional kohl application in three progressively thicker coats to the waterline, tightline, and upper lid, left unsmudged for precise architectural definition with no smear and no fadeout.',
    aestheticBio: 'Savitri Kapoor learned her craft watching the women of Old Delhi prepare for weddings the way they had for generations. Her brides are architecturally correct: kohl applied in exact strokes, sindoor placement deliberate, mogra braid weight-bearing and ceremonially sound. She is the custodian of a visual grammar that predates social media by four hundred years.',
    moodKeywords: ['ancestral', 'ceremonial', 'traditional', 'exact', 'deliberate'],
    contraIndicators: ['no-airbrush', 'no-at-home-service'],
    contraIndicatorsNotes: 'Savitri works only from her Malviya Nagar studio. The ceremonial integrity of her preparation method requires her studio environment and cannot be replicated on-site.',
  },
  portfolio: [
    {
      imageUrl: '/images/the-malviya-bride-portfolio-01.png',
      altText: 'The Malviya Bride bridal look — red Banarasi silk with triple-coat kohl',
      primaryOccasion: 'wedding-day-bridal',
      styleArchetypesShown: ['old-delhi-heritage', 'heavy-royal-mughlai'],
      colorPaletteShown: ['saffron-and-vermillion-traditional', 'ivory-and-gold-neutral'],
      captionForAI: 'Bride in red Banarasi silk, heavy gold zari. Triple-coat kohl to orbital bone, unsmudged. Vermillion sindoor placement. Structured mogra braid, heavy gold passa. Red, gold. Traditional mandap.',
      isHeroImage: true,
      sortOrder: 0,
    },
    {
      imageUrl: '/images/the-malviya-bride-portfolio-02.png',
      altText: 'The Malviya Bride baraat look — deep green Kanjivaram',
      primaryOccasion: 'baraat-reception',
      styleArchetypesShown: ['old-delhi-heritage'],
      colorPaletteShown: ['jewel-tone-maximalist', 'ivory-and-gold-neutral'],
      captionForAI: 'Baraat reception. Deep green Kanjivaram, gold border. Defined kohl, no other colour. Luminous matte skin. Low mogra chignon, single gold passa. Deep green, gold, ivory. Natural morning light.',
      isHeroImage: false,
      sortOrder: 1,
    },
    {
      imageUrl: '/images/the-malviya-bride-portfolio-03.png',
      altText: 'The Malviya Bride mehendi look — mustard raw silk saree',
      primaryOccasion: 'mehendi-ceremony',
      styleArchetypesShown: ['old-delhi-heritage'],
      colorPaletteShown: ['saffron-and-vermillion-traditional', 'earth-and-terracotta-organic'],
      captionForAI: 'Mehendi ceremony. Mustard raw silk saree. Bare skin, natural lip stain. No eye makeup. Hair in loose mogra braid with marigold clusters. Mustard, terracotta. Outdoor afternoon light.',
      isHeroImage: false,
      sortOrder: 2,
    },
    {
      imageUrl: '/images/the-malviya-bride-portfolio-03.png',
      altText: 'The Malviya Bride sangeet look — wine Banarasi with gold passa',
      primaryOccasion: 'sangeet-night-glam',
      styleArchetypesShown: ['heavy-royal-mughlai', 'old-delhi-heritage'],
      colorPaletteShown: ['deep-burgundy-and-plum-moody', 'ivory-and-gold-neutral'],
      captionForAI: 'Sangeet night. Wine Banarasi choli, ivory skirt. Extended kohl eye, wine-toned lip. Matte skin. High structured chignon, gold passa. Wine, ivory, gold. Indoor warm ambient light.',
      isHeroImage: false,
      sortOrder: 3,
    },
  ],
  ratings: {
    averageRating: 4.9,
    totalReviews: 203,
    skillScore: 5.0,
    punctualityScore: 4.9,
    communicationScore: 4.8,
    valueScore: 5.0,
  },
  flags: {
    isActive: true,
    isVerified: true,
    isFeatured: false,
    badgeType: 'Heritage Master',
  },
};

export const vendorSeedData = [
  studioNoor,
  meherAtelier,
  studioAara,
  priyaBhandariArtistry,
  theRiyaEdit,
  kamakshiAndCo,
  safiyaStudio,
  theMalviyaBride,
];

export const buildServiceSeedData = (vendorIdMap: Map<string, Types.ObjectId>) => {
  const getId = (slug: string): Types.ObjectId => {
    const id = vendorIdMap.get(slug);
    if (!id) throw new Error(`Vendor ID not found for slug: ${slug}`);
    return id;
  };

  return [
    {
      vendor: getId('studio-noor'),
      name: 'The Noor Bridal Edit',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'The Noor Bridal Edit is the studio\'s flagship service and the look for which Noor Chauhan built her reputation. Beginning with a skin assessment in the week prior, the look is constructed on event day over a four-to-five hour session — no airbrush, no heavy contouring, the finish botanical and tactile. This service includes Noor\'s signature mogra hairline placement.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 300,
        additionalPersonMinutes: 0,
        bufferMinutes: 30,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 95000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal'],
        styleArchetypeTags: ['sabyasachi-minimalist', 'raw-mango-organic'],
        aiDescription: 'Full bridal look: botanical skin prep, mogra hairline placement, kohl waterline, bare satin finish. Sabyasachi minimal aesthetic. Designed for natural and editorial light.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('studio-noor'),
      name: 'Bridesmaid Botanical Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A tonal bridesmaid look built to complement the Noor Bridal Edit. The same skin-first philosophy — satin finish, minimal colour, defined brow — scaled for the wedding party. Includes Noor\'s signature mogra stem placement in an updo or braid. Designed for ivory, terracotta, and dusty-rose bridal party ensembles.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 90,
        additionalPersonMinutes: 60,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 18000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Wedding Party Discount' },
          { minQuantity: 5, discountPercent: 16, tierLabel: 'Full Botanical Squad' },
        ],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Bridesmaids',
        minQuantity: 1,
        maxQuantity: 10,
        defaultQuantity: 3,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'sangeet-night-glam'],
        styleArchetypeTags: ['sabyasachi-minimalist', 'raw-mango-organic'],
        aiDescription: 'Bridesmaid look: satin skin, defined brow, mogra stem in low bun. Tonal match to Noor bridal palette. Ivory and terracotta coordination. Natural light optimised.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('studio-noor'),
      name: 'Noor Bridal Trial Session',
      slug: 'bridal-trial-session',
      category: 'bridal-beauty',
      serviceRole: 'trial',
      description: 'A three-hour trial session in which Noor constructs the full bridal look on the client for assessment in natural and flash photography. The session results in a detailed look card archived for event day. The full session fee is credited toward the Noor Bridal Edit booking upon confirmation.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 180,
        additionalPersonMinutes: 0,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 15000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: false,
        trialCreditINR: 15000,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'pre-wedding-shoot'],
        styleArchetypeTags: ['sabyasachi-minimalist', 'raw-mango-organic'],
        aiDescription: 'Trial session: full botanical bridal look test run. Photography assessment in natural and flash. Full fee credited toward anchor booking on confirmation.',
      },
      checkoutMeta: {
        checkoutCategory: 'optional',
        displayPriority: 10,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('meher-atelier'),
      name: 'The Mughlai Sovereign Look',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Meher Reza\'s most demanding and most sought-after service. A six-hour preparation encompassing custom kohl compound application, full airbrush base, mogra braid construction, and gold passa placement. The result is a bridal look sourced from a Mughlai court vocabulary that has no contemporary comparison in the Delhi market.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 360,
        additionalPersonMinutes: 0,
        bufferMinutes: 30,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 115000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'baraat-reception'],
        styleArchetypeTags: ['heavy-royal-mughlai', 'old-delhi-heritage'],
        aiDescription: 'Full Mughlai sovereign look: triple-coat kohl to orbital bone, heavy gold passa, mogra-woven braid, luminous matte airbrush base. Built for mandap and candlelit reception.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: true,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('meher-atelier'),
      name: 'Wedding Party Royal Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A scaled Mughlai-adjacent look for the wedding party, maintaining the regal colour vocabulary and skin luminosity of the Meher Atelier aesthetic. Each party member receives a defined kohl eye, luminous airbrush base, and a fresh mogra stem placement. Designed for jewel-toned and saffron bridal party ensembles.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 105,
        additionalPersonMinutes: 75,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 22000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Royal Party Discount' },
          { minQuantity: 6, discountPercent: 18, tierLabel: 'Full Court Rate' },
        ],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Party Members',
        minQuantity: 1,
        maxQuantity: 12,
        defaultQuantity: 3,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'sangeet-night-glam', 'baraat-reception'],
        styleArchetypeTags: ['heavy-royal-mughlai', 'old-delhi-heritage'],
        aiDescription: 'Wedding party look: defined kohl eye, luminous airbrush base, mogra placement. Mughlai colour vocabulary. Jewel-tone and saffron coordination. Regal party aesthetic.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('meher-atelier'),
      name: 'Meher Bridal Trial Session',
      slug: 'bridal-trial-session',
      category: 'bridal-beauty',
      serviceRole: 'trial',
      description: 'Meher conducts a full trial in which the complete Mughlai Sovereign Look is assembled and photographed across multiple lighting conditions. A look card is produced and archived. The trial fee is credited in full toward the Mughlai Sovereign Look booking fee upon confirmation.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 210,
        additionalPersonMinutes: 0,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 18000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: false,
        trialCreditINR: 18000,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal'],
        styleArchetypeTags: ['heavy-royal-mughlai', 'old-delhi-heritage'],
        aiDescription: 'Mughlai bridal trial: full look construction and multi-light photography assessment. Look card produced. Full fee credited toward anchor booking on confirmation.',
      },
      checkoutMeta: {
        checkoutCategory: 'optional',
        displayPriority: 10,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('studio-aara'),
      name: 'Glass Skin Bridal Look',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Studio Aara\'s signature bridal service, built around the twelve-step skin preparation protocol that begins forty-eight hours before event day. The result is a dewy, luminous base that requires no retouching under any lighting condition. Hair styling and full-day touch-up guidance is included. Best suited for brides planning both outdoor and indoor photography sessions.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 270,
        additionalPersonMinutes: 0,
        bufferMinutes: 30,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 75000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'pre-wedding-shoot'],
        styleArchetypeTags: ['glass-skin-glam', 'contemporary-editorial'],
        aiDescription: 'Korean-protocol glass-skin bridal look: twelve-step prep, zero-powder dewy base, inner corner highlight, sleek bridal updo. Photography-first performance in all lighting.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('studio-aara'),
      name: 'Bridesmaid Glass Skin Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A photography-optimised bridesmaid look matching the Studio Aara glass-skin aesthetic. Each party member receives a dewy, luminous base in their individual skin tone, a defined brow, and a soft eye suited for both natural and professional flash photography.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 90,
        additionalPersonMinutes: 60,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 14000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Wedding Party Discount' },
          { minQuantity: 6, discountPercent: 17, tierLabel: 'Full Glass Squad' },
        ],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Bridesmaids',
        minQuantity: 1,
        maxQuantity: 12,
        defaultQuantity: 3,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'pre-wedding-shoot', 'cocktail-pre-wedding'],
        styleArchetypeTags: ['glass-skin-glam'],
        aiDescription: 'Bridesmaid glass-skin look: dewy luminous base per skin tone, defined brow, soft eye. Champagne and blush palette. Optimised for flash and natural light photography.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('priya-bhandari-artistry'),
      name: 'The Priya Cinematic Look',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Priya Bhandari\'s signature cinematic bridal look, built for brides who want to be visually commanding. Includes the dual-tone cut crease, plum-to-nude lip gradient, HD skin base, and champagne brow bone highlight. Constructed under professional studio lighting with continuous camera assessment. Duration: four to five hours.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 270,
        additionalPersonMinutes: 0,
        bufferMinutes: 30,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 72000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: false,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'sangeet-night-glam', 'baraat-reception'],
        styleArchetypeTags: ['manish-malhotra-shimmer', 'dark-romanticism'],
        aiDescription: 'Cinematic bridal look: smoked cut crease in champagne and graphite, plum-to-nude lip gradient, champagne brow bone highlight, HD skin. Bollywood editorial aesthetic.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('priya-bhandari-artistry'),
      name: 'Bridesmaid Glam Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A cinematic-palette bridesmaid look scaled from the Priya Cinematic bridal aesthetic. Each party member receives a defined eye in the champagne-and-plum family, a satin skin base, and a tonal lip. Suited for jewel-tone and burgundy wedding party ensembles.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 90,
        additionalPersonMinutes: 60,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 13000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Wedding Party Discount' },
          { minQuantity: 6, discountPercent: 17, tierLabel: 'Full Cinematic Squad' },
        ],
        travelSurchargeApplicable: false,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Bridesmaids',
        minQuantity: 1,
        maxQuantity: 12,
        defaultQuantity: 3,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'sangeet-night-glam'],
        styleArchetypeTags: ['manish-malhotra-shimmer', 'dark-romanticism'],
        aiDescription: 'Bridesmaid cinematic look: defined eye in champagne-plum palette, satin skin base, tonal lip. Jewel-tone and burgundy ensemble coordination. HD-optimised finish.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('the-riya-edit'),
      name: 'The South Delhi Bridal Edit',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Riya Khanna\'s definitive bridal look — old-money restraint applied with couture-atelier precision. One precise liner stroke, clean skin at satin finish, a structured silk-press blowout, and a single statement jewellery piece. The look is photographed in-studio across seven lighting conditions before delivery on event day. Duration: four to five hours.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 270,
        additionalPersonMinutes: 0,
        bufferMinutes: 30,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 65000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'cocktail-pre-wedding', 'pre-wedding-shoot'],
        styleArchetypeTags: ['south-delhi-chic', 'indo-western-fusion'],
        aiDescription: 'South Delhi couture bridal look: one precise liner stroke, clean satin skin, structured silk-press blowout, old-money palette. Ivory, champagne, and monochrome.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('the-riya-edit'),
      name: 'Bridesmaid Edit Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A couture-restrained bridesmaid look designed to complement The South Delhi Bridal Edit. Clean skin, a single precisely placed stroke of liner, and a structured half-updo. Designed for champagne, ivory, and blush bridal party ensembles.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 90,
        additionalPersonMinutes: 60,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 12000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Party Discount' },
          { minQuantity: 5, discountPercent: 16, tierLabel: 'Full Edit Squad' },
        ],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Bridesmaids',
        minQuantity: 1,
        maxQuantity: 10,
        defaultQuantity: 3,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'cocktail-pre-wedding'],
        styleArchetypeTags: ['south-delhi-chic'],
        aiDescription: 'Bridesmaid couture-restrained look: precise liner, clean satin skin, structured half-updo. Champagne, ivory, and blush palette coordination.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('kamakshi-and-co'),
      name: 'Full Grandeur Bridal Look',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Kamakshi\'s signature Punjabi grandeur bridal look, engineered for maximum impact and maximum durability. Full dual-layer airbrush base, vivid cut crease, gajra crown construction, and deep statement lip. Rated for twelve-hour outdoor wear including baraat conditions. Duration: four hours including hair styling.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 240,
        additionalPersonMinutes: 0,
        bufferMinutes: 20,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 35000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'baraat-reception', 'sangeet-night-glam'],
        styleArchetypeTags: ['punjabi-grandeur'],
        aiDescription: 'Punjabi grandeur bridal look: dual-layer airbrush base, vivid cut crease, gajra crown, deep statement lip. Twelve-hour outdoor durability. Fuchsia, jewel tone, saffron palette.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('kamakshi-and-co'),
      name: 'Wedding Party Glam Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A full-coverage, durable bridesmaid look built for the same outdoor conditions as the Kamakshi bridal anchor. Airbrush base, defined eye in the bridal party palette, and a long-wear lip. Suitable for pastel, jewel-tone, and saffron ensembles. The most durability-optimised party look in our Cartel.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 75,
        additionalPersonMinutes: 50,
        bufferMinutes: 10,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 9000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Wedding Party Discount' },
          { minQuantity: 6, discountPercent: 18, tierLabel: 'Full Grandeur Squad' },
        ],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Party Members',
        minQuantity: 1,
        maxQuantity: 20,
        defaultQuantity: 4,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'sangeet-night-glam', 'mehendi-ceremony'],
        styleArchetypeTags: ['punjabi-grandeur'],
        aiDescription: 'Party grandeur look: airbrush base, defined eye, long-wear lip. Outdoor durability rated. Pastel, jewel-tone, saffron ensemble coordination.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('safiya-studio'),
      name: 'The Safiya Editorial Bridal',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Safiya Khan\'s flagship bridal service for the fashion-forward bride. A single, uncompromising editorial concept built around the graphic liner technique, glass-skin base, and architectural updo. Begins with a concept consultation to define the singular visual direction. Duration: four to five hours. Studio-only. Photography assessment included.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 270,
        additionalPersonMinutes: 0,
        bufferMinutes: 30,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 70000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'pre-wedding-shoot', 'cocktail-pre-wedding'],
        styleArchetypeTags: ['contemporary-editorial', 'glass-skin-glam'],
        aiDescription: 'Editorial bridal look: single-stroke angular graphic liner, glass-skin base, architectural updo, no excess colour. Fashion-first bride aesthetic. Monochrome and champagne palette.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: true,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('safiya-studio'),
      name: 'Bridesmaid Editorial Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A scaled editorial look for the Safiya bridal party. Each bridesmaid receives a graphic liner, glass-skin base, and a clean half-updo, maintaining the fashion-editorial aesthetic of the anchor look. Designed for monochrome, champagne, and ivory ensemble palettes.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 90,
        additionalPersonMinutes: 60,
        bufferMinutes: 15,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 13000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Editorial Party Discount' },
          { minQuantity: 5, discountPercent: 16, tierLabel: 'Full Editorial Squad' },
        ],
        travelSurchargeApplicable: true,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Bridesmaids',
        minQuantity: 1,
        maxQuantity: 10,
        defaultQuantity: 3,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'cocktail-pre-wedding', 'pre-wedding-shoot'],
        styleArchetypeTags: ['contemporary-editorial', 'glass-skin-glam'],
        aiDescription: 'Bridesmaid editorial look: graphic liner, glass-skin base, clean half-updo. Monochrome, champagne, ivory palette. Fashion-forward party coordination.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('the-malviya-bride'),
      name: 'The Heritage Bridal Look',
      slug: 'full-bridal-look',
      category: 'bridal-beauty',
      serviceRole: 'anchor',
      description: 'Savitri Kapoor\'s complete traditional bridal look, unchanged in its essential grammar for three generations. Triple-coat kohl application, ceremonially correct sindoor placement, structured mogra braid with heavy gold passa, and a luminous matte skin base. Studio-only. Duration: four hours. The definitive Delhi traditional bridal look.',
      compatibleAnchorCategories: [],
      duration: {
        baseDurationMinutes: 240,
        additionalPersonMinutes: 0,
        bufferMinutes: 20,
        canRunConcurrentlyWithAnchor: false,
      },
      pricing: {
        unitPriceINR: 28000,
        priceType: 'per-service',
        groupDiscountTiers: [],
        travelSurchargeApplicable: false,
      },
      partyConfig: {
        isQuantifiable: false,
        recipientType: 'bride',
        quantityLabel: 'Bride',
        minQuantity: 1,
        maxQuantity: 1,
        defaultQuantity: 1,
        requiresAnchorService: false,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'baraat-reception', 'mehendi-ceremony'],
        styleArchetypeTags: ['old-delhi-heritage', 'heavy-royal-mughlai'],
        aiDescription: 'Heritage bridal look: triple-coat kohl, vermillion sindoor, mogra braid, heavy gold passa, luminous matte skin. Ceremonially correct Old Delhi vocabulary. Traditional mandap-ready.',
      },
      checkoutMeta: {
        checkoutCategory: 'primary',
        displayPriority: 0,
        estimateContribution: 'fixed',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: true,
        isNewlyAdded: false,
      },
    },
    {
      vendor: getId('the-malviya-bride'),
      name: 'Wedding Party Heritage Look',
      slug: 'bridesmaid-glam',
      category: 'party-glam',
      serviceRole: 'add-on',
      description: 'A traditional bridesmaid look built from the same ceremonial vocabulary as the Malviya Bride anchor. Defined kohl eye, mogra hair placement, and a matte or satin skin base matched to each party member\'s tone. Designed for saffron, vermillion, and jewel-tone bridal party ensembles.',
      compatibleAnchorCategories: ['bridal-beauty'],
      duration: {
        baseDurationMinutes: 75,
        additionalPersonMinutes: 50,
        bufferMinutes: 10,
        canRunConcurrentlyWithAnchor: true,
      },
      pricing: {
        unitPriceINR: 8000,
        priceType: 'per-person',
        groupDiscountTiers: [
          { minQuantity: 3, discountPercent: 10, tierLabel: 'Family Discount' },
          { minQuantity: 6, discountPercent: 18, tierLabel: 'Full Heritage Party' },
        ],
        travelSurchargeApplicable: false,
      },
      partyConfig: {
        isQuantifiable: true,
        recipientType: 'bridesmaid',
        quantityLabel: 'Party Members',
        minQuantity: 1,
        maxQuantity: 15,
        defaultQuantity: 4,
        requiresAnchorService: true,
      },
      aestheticSignals: {
        occasionTags: ['wedding-day-bridal', 'mehendi-ceremony', 'baraat-reception'],
        styleArchetypeTags: ['old-delhi-heritage'],
        aiDescription: 'Heritage party look: kohl eye, mogra placement, matte-satin skin per tone. Saffron, vermillion, jewel-tone ensemble coordination. Traditional ceremonial aesthetic.',
      },
      checkoutMeta: {
        checkoutCategory: 'secondary',
        displayPriority: 1,
        estimateContribution: 'tiered',
        bundleEligible: false,
        requiresConsultation: false,
      },
      flags: {
        isActive: true,
        isSignatureService: false,
        isNewlyAdded: false,
      },
    },
  ];
};